---
apiVersion: v1
kind: Service
metadata:
  name: tiny-web
  namespace: smoke-demo
spec:
  selector:
    app: tiny-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5678
